version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/auth:/app/auth
      - ./backend/.env:/app/.env
    restart: unless-stopped
    environment:
      - TZ=Europe/Zagreb
